import { adopta1, adopta2, adopta3 } from "@public/assets"

export const data = [
        {
            id: 1,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 2,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'cat',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 3,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'male',
            type: 'cat',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 4,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 5,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 6,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 7,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses', 
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 8,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 9,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 10,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 11,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 12,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 13,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 14,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 15,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 16,
            name: 'Rosenda',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses', 
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 17,
            name: 'Wasabi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
        {
            id: 18,
            name: 'Tampico',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            img: 'https://res.cloudinary.com/factra/image/upload/v1513897596/color-umbrella-red-yellow-163822_nfwdgs.jpg',
            location: 'Margarita Castelar, Bs. A.s.',
            time: 'Hace 5 días',
            desc: 'Gatita 5 meses',
            fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nunc nisl aliquet.',
            date: '27/08/2023',
            sex: 'female',
            type: 'dog',
            contact_name: 'Juan Perez',
            contact_phone: '123456789',
        },
]